-- Auto Generated (Do not modify) 1EFB76C448210DE32027F4C27637AC8481B2BD1FBF50BB51B3D3F63BD70F5264
-- Top Selling Products View (Fixed Version)
CREATE VIEW vw_TopSellingProducts AS
SELECT 
    s.PRODUCTCODE,
    p.PRODUCTLINE,
    SUM(CAST(s.QUANTITYORDERED AS INT)) AS TotalQuantity,
    SUM(CAST(s.SALES AS DECIMAL(18,2))) AS TotalRevenue,
    RANK() OVER (ORDER BY SUM(CAST(s.SALES AS DECIMAL(18,2))) DESC) AS RevenueRank,
    RANK() OVER (ORDER BY SUM(CAST(s.QUANTITYORDERED AS INT)) DESC) AS QuantityRank
FROM fact_sales s
JOIN dim_product p ON s.PRODUCTCODE = p.PRODUCTCODE
GROUP BY s.PRODUCTCODE, p.PRODUCTLINE;